find_path(GLIB_INCLUDE_DIR NAMES glib.h PATH_SUFFIXES glib-2.0)
find_library(GLIB_LIBRARY NAMES glib-2.0 PATHS GLIB_LIBRARY_DIR HINTS /usr/lib/x86_64-linux-gnu /opt/local/lib)
get_filename_component(GLIB_LIBRARY_DIR ${GLIB_LIBRARY} DIRECTORY)
find_path(GLIB_CONFIG_INCLUDE_DIR NAMES glibconfig.h PATH_SUFFIXES glib-2.0/include PATHS ${GLIB_LIBRARY_DIR})

set(GLIB_INCLUDE_DIRS ${GLIB_INCLUDE_DIR} ${GLIB_CONFIG_INCLUDE_DIR})
set(GLIB_LIBRARIES ${GLIB_LIBRARY})

mark_as_advanced(GLIB_INCLUDE_DIRS GLIB_LIBRARIES)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(glib FOUND_VAR glib_FOUND REQUIRED_VARS GLIB_INCLUDE_DIRS GLIB_LIBRARIES)
